package Persistence;

import Model.Utilizador;

import java.sql.*;

/**
 *
 * UtilizadorRepository
 *
 * @author Davide Silva
 *
 */

public class UtilizadorRepository extends AbstractRepository<Utilizador> {

    private static final String INSERT_UTILIZADOR = "insert into utilizador (nome_utilizador, password, conta) values (?,?,?)";

    private static final String UPDATE_UTILIZADOR = "update utilizador set nome_utilizador = ?, password = ?, conta = ? where id = ?";

    private static final String SELECT_UTILIZADOR = "select nome_utilizador, password, conta from utilizador where id = ?";

    private final String url;
    private final String user;
    private final String password;

    public UtilizadorRepository(String url, String user, String password) {
        this.url = url;
        this.user = user;
        this.password = password;
    }

    @Override
    public void save(Utilizador utilizador) throws PersistenceException {
        String query;
        int autoGeneratedKeys;
        boolean isUpdate;
        if (utilizador.getId() < 0) {
            isUpdate = false;
            query = INSERT_UTILIZADOR;
            autoGeneratedKeys = Statement.RETURN_GENERATED_KEYS;
        }
        else {
            isUpdate = true;
            query = UPDATE_UTILIZADOR;
            autoGeneratedKeys = Statement.NO_GENERATED_KEYS;
        }

        try {
            Connection connection = DriverManager.getConnection(url,user,password);
            PreparedStatement statement = connection.prepareStatement(query,autoGeneratedKeys);

            statement.setString(1,utilizador.getNome());
            statement.setString(2,utilizador.getPassword());
            statement.setInt(3,utilizador.getConta());

            if (isUpdate) {
                statement.setLong(4,utilizador.getId());
            }

            statement.executeUpdate();

            try (ResultSet keys = statement.getGeneratedKeys()) {
                if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS && keys.next()) {
                    utilizador.setId(keys.getLong(1));
                } else {
                    throw new PersistenceException("Error generating id for user: " + utilizador);
                }
            } finally {
                statement.close();
                connection.close();
            }

        } catch (SQLException ex) {
            throw new PersistenceException("Error saving user: " + utilizador, ex);
        }


    }

    @Override
    public Utilizador find(long id) throws PersistenceException {
        try {
            Utilizador utilizador;

            Connection connection = DriverManager.getConnection(url,user,password);
            PreparedStatement statement = connection.prepareStatement(SELECT_UTILIZADOR);

            statement.setLong(1,id);

            try (ResultSet result = statement.executeQuery()) {
                if (result.next()) {
                    utilizador = new Utilizador();
                    utilizador.setId(id);
                    utilizador.setNome(result.getString("nome_utilizador"));
                    utilizador.setPassword(result.getString("password"));
                    utilizador.setConta(result.getInt("conta"));
                }
                else {
                    utilizador = null;
                }
            } finally {
                statement.close();
                connection.close();
            }

            return utilizador;

        } catch (SQLException ex) {
            throw new PersistenceException("Error finding user: " + id, ex);
        }
    }

    @Override
    public Iterable<Utilizador> findAll() throws PersistenceException {
        return null;
    }

    @Override
    public void delete(Utilizador utilizador) throws PersistenceException {

    }

    @Override
    public void deleteAll() throws PersistenceException {

    }

    @Override
    public long count() throws PersistenceException {
        return 0;
    }
}
