-- MySQL Script generated by MySQL Workbench
-- Wed 03 Dec 2014 16:33:18 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema habitat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema habitat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `habitat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `habitat` ;

-- -----------------------------------------------------
-- Table `habitat`.`voluntario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`voluntario` ;

CREATE TABLE IF NOT EXISTS `habitat`.`voluntario` (
  `id_voluntario` INT NOT NULL,
  `nome_voluntario` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  `profissao` VARCHAR(45) NULL,
  `morada` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(45) NULL,
  `localidade` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `telemovel` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `hab_academ` VARCHAR(45) NULL,
  `conhec_lingui` VARCHAR(45) NULL,
  `form_compl` VARCHAR(45) NULL,
  `exp_voluntariado` VARCHAR(45) NULL,
  `conhec_constr` VARCHAR(45) NULL,
  `trabalho_grupo` VARCHAR(45) NULL,
  `pub` VARCHAR(45) NULL,
  `disponi_tempo` VARCHAR(45) NULL,
  `cca_habitat` VARCHAR(45) NULL,
  PRIMARY KEY (`id_voluntario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`tarefa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`tarefa` ;

CREATE TABLE IF NOT EXISTS `habitat`.`tarefa` (
  `id_tarefa` INT NOT NULL,
  `nome_tarefa` VARCHAR(45) NULL,
  `data_inicio` VARCHAR(45) NULL,
  `data_final` VARCHAR(45) NULL,
  `id_encarregado` VARCHAR(45) NULL,
  `id_projecto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tarefa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`candidatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`candidatura` ;

CREATE TABLE IF NOT EXISTS `habitat`.`candidatura` (
  `id_candidatura` INT NOT NULL,
  `nome_candidato` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  `morada` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `estado_civil` VARCHAR(45) NULL,
  `escolaridade` VARCHAR(45) NULL,
  `profissao` VARCHAR(45) NULL,
  `naturalidade` VARCHAR(45) NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `aprovado` TINYINT(1) NULL,
  PRIMARY KEY (`id_candidatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`projecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`projecto` ;

CREATE TABLE IF NOT EXISTS `habitat`.`projecto` (
  `id_projecto` INT NOT NULL,
  `nome_projecto` VARCHAR(45) NULL,
  `data_inicio` VARCHAR(45) NULL,
  `data_final` VARCHAR(45) NULL,
  `custo_inicio` VARCHAR(45) NULL,
  `custo_final` VARCHAR(45) NULL,
  `classificacao` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `candidatura` INT NOT NULL,
  `tarefa` INT NOT NULL,
  PRIMARY KEY (`id_projecto`, `candidatura`, `tarefa`),
  INDEX `fk_candidatura_idx` (`candidatura` ASC),
  UNIQUE INDEX `candidatura_UNIQUE` (`candidatura` ASC),
  INDEX `fk_tarefa_idx` (`tarefa` ASC),
  CONSTRAINT `fk_candidatura`
    FOREIGN KEY (`candidatura`)
    REFERENCES `habitat`.`candidatura` (`id_candidatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarefa`
    FOREIGN KEY (`tarefa`)
    REFERENCES `habitat`.`tarefa` (`id_tarefa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`voluntario_tarefa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`voluntario_tarefa` ;

CREATE TABLE IF NOT EXISTS `habitat`.`voluntario_tarefa` (
  `id_voluntario` INT NOT NULL,
  `id_tarefa` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `nr_horas` VARCHAR(45) NULL,
  PRIMARY KEY (`id_voluntario`, `id_tarefa`),
  INDEX `fk_id_tarefa_idx` (`id_tarefa` ASC),
  CONSTRAINT `fk_id_voluntario`
    FOREIGN KEY (`id_voluntario`)
    REFERENCES `habitat`.`voluntario` (`id_voluntario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_tarefa`
    FOREIGN KEY (`id_tarefa`)
    REFERENCES `habitat`.`tarefa` (`id_tarefa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`evento` ;

CREATE TABLE IF NOT EXISTS `habitat`.`evento` (
  `id_evento` INT NOT NULL,
  `nome_evento` VARCHAR(45) NULL,
  `data_evento` VARCHAR(45) NULL,
  `valor_total` VARCHAR(45) NULL,
  `organizador` VARCHAR(45) NULL,
  `notas` VARCHAR(45) NULL,
  PRIMARY KEY (`id_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`doador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`doador` ;

CREATE TABLE IF NOT EXISTS `habitat`.`doador` (
  `id_doador` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `morada` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `pessoa_contacto` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  `notas` VARCHAR(45) NULL,
  PRIMARY KEY (`id_doador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`doacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`doacoes` ;

CREATE TABLE IF NOT EXISTS `habitat`.`doacoes` (
  `id_doacao` INT NOT NULL,
  `doador` INT NOT NULL,
  `evento` INT NULL,
  PRIMARY KEY (`id_doacao`, `doador`, `evento`),
  UNIQUE INDEX `id_doacao_UNIQUE` (`id_doacao` ASC),
  INDEX `fk_doacoes_1_idx` (`doador` ASC),
  INDEX `fk_evento_idx` (`evento` ASC),
  CONSTRAINT `fk_doacoes_1`
    FOREIGN KEY (`doador`)
    REFERENCES `habitat`.`doador` (`id_doador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento`
    FOREIGN KEY (`evento`)
    REFERENCES `habitat`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`material_projecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`material_projecto` ;

CREATE TABLE IF NOT EXISTS `habitat`.`material_projecto` (
  `id_material` INT NOT NULL,
  `projecto_id` INT NOT NULL COMMENT 'I   	 ',
  `quant_necessaria` VARCHAR(45) NULL,
  `quant_actual` VARCHAR(45) NULL,
  `motivo` VARCHAR(45) NULL,
  `doacao` INT NOT NULL,
  PRIMARY KEY (`id_material`, `projecto_id`, `doacao`),
  INDEX `fk_material_projecto_1_idx` (`doacao` ASC),
  INDEX `fk_projecto_idx` (`projecto_id` ASC),
  CONSTRAINT `fk_material_projecto_1`
    FOREIGN KEY (`doacao`)
    REFERENCES `habitat`.`doacoes` (`id_doacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projecto`
    FOREIGN KEY (`projecto_id`)
    REFERENCES `habitat`.`projecto` (`id_projecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`grupo` ;

CREATE TABLE IF NOT EXISTS `habitat`.`grupo` (
  `id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`grupo_voluntario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`grupo_voluntario` ;

CREATE TABLE IF NOT EXISTS `habitat`.`grupo_voluntario` (
  `id_voluntario` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_voluntario`, `id_grupo`),
  INDEX `fk_id_grupo_idx` (`id_grupo` ASC),
  CONSTRAINT `fk_id_voluntario`
    FOREIGN KEY (`id_voluntario`)
    REFERENCES `habitat`.`voluntario` (`id_voluntario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_grupo`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `habitat`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`agregado_familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`agregado_familiar` ;

CREATE TABLE IF NOT EXISTS `habitat`.`agregado_familiar` (
  `id_agreg_fam` INT NOT NULL,
  `candidatura` INT NOT NULL,
  PRIMARY KEY (`id_agreg_fam`, `candidatura`),
  INDEX `fk_candidatura_idx` (`candidatura` ASC),
  CONSTRAINT `fk_candidatura`
    FOREIGN KEY (`candidatura`)
    REFERENCES `habitat`.`candidatura` (`id_candidatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `habitat`.`pessoa` (
  `id_pessoa` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `parentesco` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  `estado_civil` VARCHAR(45) NULL,
  `ocupacao` VARCHAR(45) NULL,
  `escolaridade` VARCHAR(45) NULL,
  `agreg_fam_id` INT NOT NULL,
  PRIMARY KEY (`id_pessoa`, `agreg_fam_id`),
  INDEX `fk_pessoa_1_idx` (`agreg_fam_id` ASC),
  CONSTRAINT `fk_pessoa_1`
    FOREIGN KEY (`agreg_fam_id`)
    REFERENCES `habitat`.`agregado_familiar` (`id_agreg_fam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habitat`.`utilizador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habitat`.`utilizador` ;

CREATE TABLE IF NOT EXISTS `habitat`.`utilizador` (
  `id_utilizador` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `nome_utilizador` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id_utilizador`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
